{% set version = "0.0-9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assertive.base
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/assertive.base_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.base/assertive.base_{{ version }}.tar.gz
  sha256: 4bf0910b0eaa507e0e11c3c43c316b524500c548d307eb045d6f89047e6ba01e

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('assertive.base')"           # [not win]
    - "\"%R%\" -e \"library('assertive.base')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.base
  license: GPL-3.0-or-later
  summary: A minimal set of predicates and assertions used by the assertive package.  This is mainly for use by other package developers who want to include run-time testing features in their own packages.  End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
