{% set version = '0.0-7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assertive.base
  version: {{ version|replace("-", "_") }}

source:
  fn: assertive.base_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/assertive.base_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.base/assertive.base_{{ version }}.tar.gz
  sha256: f02d4eca849f512500abb266a2a751d1fa2cf064f7142e5161a77c20b7f643f7

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('assertive.base')"           # [not win]
    - "\"%R%\" -e \"library('assertive.base')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.base
  license: GPL (>= 3)
  summary: A minimal set of predicates and assertions used by the assertive package.  This is
    mainly for use by other package developers who want to include run-time testing
    features in their own packages.  End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - jenzopr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
