# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J0xrTa3m1eqZ0tQ9TnYWGXf7AX68lwYxeMv5QY5KunUPBZ8V5eEdoHuyaRO9c2XZwXc3AXZqYQKuIP6QsEUyd3dYyJkEbqvnqZRQxG0Mm07pa3+WnAd1vsYmBTEXScguEp0wb2hdN2+2YGBJLXYj8QOzUZn9a4Mjh7bGNd0t0SS3Ieo6F+9ofAIz8mqiiIWlRdd4yrsEBVhUsDX5I3AFvgg22XdT5OGLvCeMItYF2GXLy8dtg1inlYcwbb8ANeGWfcCEhAKwopEsS0/rhnXsM+jUcQmvwF8dFEG5XYu2HGbw860rVaNbLRc7cYahaJrHSOb+nPVRZ9PlCt180TD8tOXNIIPr2GMEMSDvAKeY8PfxC0hSNR2qclaufeHzfNO4Y0YWNSWJiq/xF7cirT5UojAFMvBoTAhwDAhKcOeoXKklJvAdz83HCNmp/8qR8EaeEmFcuz3ravDPI3Bu6VQgxxcvcZoEEdpt+JtTlfm+23OoSqM91uld8zm5cjFsiBFh7KhyQSBe5zBt1dAU2gdhzp0wyEHTYuXLU5TAqMq4w19EqAuUQvEvdtfTsQ6FHMknvyQn/ManGRAODMFNXLL5/jTDlkmuyJFwR+obPyi4yYkg54rysZ5v8OUzZXsHLDt8mjGQR9vb+PX8fiZgyhtRv2Dfgldvw/B6YtXGvSo4bN0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
